name: books
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  persistent_bottom_nav_bar: ^5.0.2
  flutter:
    sdk: flutter
  http: ^1.1.0
  google_fonts: ^6.1.0
  faker: ^2.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/profile.png
    - assets/images/icon_settings.png
